name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Check syntax
      run: |
        python -c "import models.book, models.ebook, models.printed_book, models.user, services.payment, services.library"
        echo "All imports work"
        
    - name: Run tests
      run: |
        python -m unittest discover tests
        
    - name: Run application
      run: python main.py