name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@vv4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Test Python syntax
      run: |
        python -m py_compile models/*.py
        python -m py_compile services/*.py
        python -m py_compile main.py
        echo "✅ Syntax check passed"
        
    - name: Run basic test
      run: |
        python -c "from models.ebook import EBook; from models.printed_book import PrintedBook; from datetime import date; ebook = EBook('Test', 'Author', '123', date(2023,1,1), 5.0); pbook = PrintedBook('Test', 'Author', '456', date(2023,1,1), 300); print('✅ Objects created'); print('✅ EBook fee:', ebook.calculate_late_fee(5)); print('✅ Printed fee:', pbook.calculate_late_fee(5)); print('🎉 Basic test passed')"
        
    - name: Run main app
      run: |
        python main.py
